testing:
  hosts:
    testmachine:
      ansible_port: 2220
      ansible_ssh_private_key_file: ".vagrant/machines/testmachine/virtualbox/private_key"
  vars:
    host_group: "test"
all:
  vars:
      commontoall: thisvar
      anothercommontoall: thisvar
      ansible_user: vagrant
      ansible_host: 127.0.0.1
      ansible_ssh_password: "vagrant"
      ansible_ssh_pass: "vagrant"
      ansible_ssh_private_key: '~/.ssh/id_rsa' 
      ansible_host_key_checking: false
      ansible_ssh_path_main0: "./vagrant/machines/"
      ansible_ssh_path_main1: "/virtualbox/private_key"


